/*
 This file was generated by Dashcode and is covered by the
 license.txt included in the project.  You may edit this file,
 however it is recommended to first turn off the Dashcode
 code generator otherwise the changes will be lost.
 */
var attributes = {
    "blinkSeparators": "0",
    "doAction": "0",
    "iCalEventSummary": "",
    "reachedActionIndex": "1",
    "sharediCalURL": "",
    "showLeadingZeros": "1",
    "targetDateTime": new Date("13 Jul 2014 16:00:00 -0500"),
    "targetKind": "0",
    "zeroAction": "alert(\"Llegó la hora\")"
};

